### ISSUE TITLE
With the latest update of Windows 10, when opening a link, it only opens the selected browser and nothing else

### ISSUE THREAD

**Issue by NeoSDAP** [rcmaehl/MSEdgeRedirect#127] opened 2022-04-26 13:40 UTC
I just upgraded to Windows 10 Pro build 19044.1682 using optional update [KB5011831](https://support.microsoft.com/en-us/topic/april-25-2022-kb5011831-os-builds-19042-1682-19043-1682-and-19044-1682-preview-fe4ff411-d25a-4185-aabb-8bc66e9dbb6c).

After finishing the restart, when you open a link, from Weather or news and interests, now it only opens the default browser (in my case, Chrome), without opening the link and nothing else.

**Comment by rcmaehl** [comment] 2022-04-26 13:50
Duplicate of #121 but good to have an update number. I'll look into this now that it's in stable.

**Closed** 2022-04-26 13:51 UTC
