### ISSUE TITLE
Links coming from teams opens url https://decodedurl/

### ISSUE THREAD

**Issue by allycruzr** [rcmaehl/MSEdgeRedirect#389] opened 2024-02-05 11:46 UTC
Hi there! 
The test case with microsoft-edge:https://www.ctrl.blog works. 
But links coming from teams opens url https://decodedurl/
thanks for having a look :D

**Comment by ixzess** [comment] 2024-02-21 10:19
Anything new here? Links from Microsoft Outlook the same for me.

**Comment by rcmaehl** [comment] 2024-03-03 03:27
Working on this. If you have the ability, in Outlook Advanced Options you can set it to your default browser.

Closing as duplicate of #331 and tracking issue there

**Closed by rcmaehl** 2024-03-03 03:27 UTC
