### ISSUE TITLE
Add ability to automatically download updates

### ISSUE THREAD

**Issue by udobehm** [rcmaehl/MSEdgeRedirect#150] opened 2022-07-02 16:14 UTC
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Unsure

### Steps to reproduce

Good day. I got the message that an update to version 0.7 is available. I wanted to install it but the installer doesn't start after I downloaded the new 64 bit version. What can I do?

By the way: Can you manage auto updates? Would like your tool to update itself, if possible, not having to download any exe files anmyore. Thank you also for the tool.

### ✔️ Expected Behavior

Installer opening

### ❌ Actual Behavior

No installation appeared. Installation of new version 0.7 fails. I uninstalled EdgeRedirect and tried to install the new installation first. Still no installer and no update possible...

### Microsoft Windows version

Win 11, Ver 22H2 (Build 22621.160)

**Comment by rcmaehl** [comment] 2022-07-02 17:16
Can you show the file properties of the downloaded installer? I haven't heard any other issues.

For the auto updates, I'll add it to the 0.8.0.0 TODO

**Comment by udobehm** [comment] 2022-07-02 18:18
Sure. I suppose I should see an installer after opening the file, is that correct?
![Screenshot 2022-07-02 201723](https://user-images.githubusercontent.com/50866188/177012085-9e601d09-d14c-4bba-9e97-a708915c1590.jpg)

**Comment by rcmaehl** [comment] 2022-07-02 19:35
> Sure. I suppose I should see an installer after opening the file, is that correct?

Yes.

![image](https://user-images.githubusercontent.com/716581/177014112-32e4ad0e-f9df-4d94-8f5e-ba1576b642af.png)

In the `Allgemein` tab if there's an option to `Unblock` go ahead and try that, then running it again.

**Comment by udobehm** [comment] 2022-07-02 20:13
That's crazy. Now Microsoft blocks even software without showing that it could be run when executing a file (bringing up a warning, that the file isn't safe as it used to be before). Thanks for that tip! Now it is working

**Comment by udobehm** [comment] 2022-07-03 18:08
Is this new to Windows or is it just a single case with your file?

**Comment by rcmaehl** [comment] 2022-07-03 18:10
> Is this new to Windows or is it just a single case with your file?

It's been around since [2015 at least](https://winaero.com/how-to-unblock-files-downloaded-from-internet-in-windows-10/) but is uncommon.

**Comment by udobehm** [comment] 2022-07-03 18:14
Yes, normally I got this blue message and I could click on "More info" and allow the file to be executed. However with your file no more blue box appeared. Just nothing happened until you told me I could go to file properities and allow access from there.
I wonder whether Microsoft has worsened the procedure of such files, giving no more ability to open it at all (if you do not know the workaround with the properities dialogue)

**Comment by sgpascoe** [comment] 2022-11-02 13:38
Oh god yes please I don't want to visit this page every week

**Comment by PROX1MO** [comment] 2023-06-10 14:40
Hello, i am using this app at home and it works just fine. At work i use it in portable mode, because when installed all settings are written to:
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\MSEdgeRedirect
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\MSEdgeRedirect
And these locations are being monitored for unwanted software. I don't mind using it portable, the problem is that it is not working correctly when in that mode, Sometimes it redirects and sometimes does not. I wish portable mode is fixed in the next version or install does not use the mentioned locations above for storing settings, so i can delete the entries safely

**Comment by rcmaehl** [comment] 2023-11-16 03:26
Merging with 1.0.0.0 checklist

**Closed by rcmaehl** 2023-11-16 03:26 UTC
Labels: enhancement
