### ISSUE TITLE
Auto-update popup provides no information about what exactly is asking to be updated

### ISSUE THREAD

**Issue by ItsMeAubey** [rcmaehl/MSEdgeRedirect#101] opened 2022-03-14 17:47 UTC
**Describe the request**
I just got a popup stating that there was an update, and that I could click a button to be brought to the update page. It said nothing about what software had an update, literally just a basic window with "there is an update, do you want to update?". I clicked the yes button and it brought me to the download page for MSEdgeRedirect. I think that the auto-update notifier window should be modified to show that the window is from MSEdgeRedirect. 

https://github.com/rcmaehl/MSEdgeRedirect/blob/faf2f12ce2e11d79d434ae15226374427d0750c5/MSEdgeRedirect_Wrapper.au3#L679

This seems to be the exact text I saw. 

**Screenshots**
Unfortunately I did not have the foresight to take a screenshot.

**Comment by rcmaehl** [comment] 2022-03-14 17:58
The vagueness was leftover from when it was a manual update checker. Closing as duplicate of #98 and #65

**Closed by rcmaehl** 2022-03-14 17:58 UTC
Labels: duplicate, enhancement

**Comment by ItsMeAubey** [comment] 2022-03-14 18:02
Thanks :) My apologies for the duplicate issue.
