### ISSUE TITLE
AutoIt Error Line 1590

### ISSUE THREAD

**Issue by 1keepon** [rcmaehl/MSEdgeRedirect#208] opened 2022-10-13 16:35 UTC
10 13 2022 Thurs.
Good Morning
I'm just a user of Edge Redirect & grateful for it.
I keep getting the 'line 1590' error & have NO idea of how to correct it.  
I've been reading github but have no clue what you folks are talking about "Array variables subscripts," etc.  
I KNOW Edge tried mighttily to block my use of Redirect, but also saw reference to Google interfering with Redirect.
Is there a FIX for this 1590 error?  Are we FORCED to use Edge?
![10 13 2022 AutoIt Line 1590](https://user-images.githubusercontent.com/108579334/195652673-835f688c-c5fd-4823-94b2-5fa7f76e7766.PNG)
Apologies in advance for my lack of understanding.  
IS REDIRECT USABLE?  Has it been intentionally sabotaged to force us back to using edge?

**Comment by rcmaehl** [comment] 2022-10-13 17:47
Duplicate of #195 
Please try the latest 0.8.0.0 test build.

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

**Closed by rcmaehl** 2022-10-13 17:47 UTC

**Comment by 1keepon** [comment] 2022-10-13 22:48
Robert !!  Thanks for taking time for me and responding so quickly!Below you'll see what I meant by 'are both Edge & Google sabotagging' your Redirect, your effort to allow us choice of browser.When I clicked the link you provided to fix Redirect, Chrome tells me ' Don't click it !!!  It's evil.' I'm going to try & force my way thru, but is that what caused my / our 1590 "errors?"  No error on your part.Well...here goes.




    On Thursday, October 13, 2022 at 01:47:52 PM EDT, Robert C. Maehl ***@***.***> wrote:  
 
 


Duplicate of #195
Please try the latest 0.8.0.0 test build.

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

**Comment by 1keepon** [comment] 2022-10-13 22:59
6:54 pm N.J.This is whaqt it gives me:     

    On Thursday, October 13, 2022 at 06:48:26 PM EDT, ***@***.*** ***@***.***> wrote:  
 
  Robert !!  Thanks for taking time for me and responding so quickly!Below you'll see what I meant by 'are both Edge & Google sabotagging' your Redirect, your effort to allow us choice of browser.When I clicked the link you provided to fix Redirect, Chrome tells me ' Don't click it !!!  It's evil.' I'm going to try & force my way thru, but is that what caused my / our 1590 "errors?"  No error on your part.Well...here goes.




    On Thursday, October 13, 2022 at 01:47:52 PM EDT, Robert C. Maehl ***@***.***> wrote:  
 
 


Duplicate of #195
Please try the latest 0.8.0.0 test build.

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

**Comment by 1keepon** [comment] 2022-10-13 23:14
7:11
It will not let me thru.  It will not allow me to use the repair you have provided. guess it just wants me to DELETE EDGE ?Thanks for your effort.
   ----- Forwarded Message ----- From: ***@***.*** ***@***.***>To:Sent: Thursday, October 13, 2022 at 06:59:35 PM EDTSubject: Re: [rcmaehl/MSEdgeRedirect] AutoIt Error Line 1590 (Issue #208)
  6:54 pm N.J.This is whaqt it gives me:     

    On Thursday, October 13, 2022 at 06:48:26 PM EDT, ***@***.*** ***@***.***> wrote:  
 
  Robert !!  Thanks for taking time for me and responding so quickly!Below you'll see what I meant by 'are both Edge & Google sabotagging' your Redirect, your effort to allow us choice of browser.When I clicked the link you provided to fix Redirect, Chrome tells me ' Don't click it !!!  It's evil.' I'm going to try & force my way thru, but is that what caused my / our 1590 "errors?"  No error on your part.Well...here goes.




    On Thursday, October 13, 2022 at 01:47:52 PM EDT, Robert C. Maehl ***@***.***> wrote:  
 
 


Duplicate of #195
Please try the latest 0.8.0.0 test build.

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip
