### ISSUE TITLE
Not working when edge is removed

### ISSUE THREAD

**Issue by wmaniac** [rcmaehl/MSEdgeRedirect#27] opened 2021-12-09 21:59 UTC
Hi,

I have uninstalled edge (chromium) and edge legacy using NTlite, then there is nomore  microsoft-edge protocol handler.

So  MSEdgeRedirect will not work.

Thank you.

**Comment by rcmaehl** [comment] 2021-12-09 22:05
Duplicate of #26. Working on a fix.

**Closed by rcmaehl** 2021-12-09 22:05 UTC
Labels: bug, duplicate
