### ISSUE TITLE
The site ahead may contain harmful programs

### ISSUE THREAD

**Issue by JakeQZ** [rcmaehl/MSEdgeRedirect#406] opened 2024-03-24 22:44 UTC
**Describe the request**
The software seems have been flagged by 'Google Safe Browsing' as "harmful".

**Screenshots**
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/15205088/fb6f1eb5-2f89-4317-9645-bd65c97e8fba)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - 22H2 Build 19045.4170

**Browser**
- Firefox 124.0.1 (64-bit)

**Additional context**
On upgrade - "A new version is available, would you like to download?" (or suchlike).  This leads to the URL `https://github.com/rcmaehl/MSEdgeRedirect/releases/tag/0.7.5.3` being opened in Firefox, and the above warning being shown.  Other release pages on GitHub do not generate this warning.

**Comment by rcmaehl** [comment] 2024-03-26 10:49
Duplicate of #160.

It's always a specific page to as if it's being targeted. Working on this again...

**Closed by rcmaehl** 2024-03-26 10:49 UTC
Labels: enhancement
