### ISSUE TITLE
Cannot close Microsoft Edge

### ISSUE THREAD

**Issue by shanekelly55** [rcmaehl/MSEdgeRedirect#95] opened 2022-03-12 01:16 UTC
**Check List**
- [ x] Microsoft Edge is still installed (see issue 26)
- [ x] Running `microsoft-edge:https://google.com` redirects successfully
- [ x] Reinstall or `/repair` was attempted for System Errors (see issues 25 & 77)
- [ x] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

**Install Type**
- [ x] New Install
- [ ] New Deployment (winget/chocolatey/sccm)
- [ ] Update
- [ ] Managed Update (winget/chocolatey/sccm)

**Installed Mode**
- [ x] Active Mode
- [ ] Service Mode
- [ ] Unsure

**Describe the bug**

I cannot open Edge from the Start Menu.  I have to go to the Apps section and open from there.  Once opened, i cannot close Edge.

**To Reproduce**
1. Open Edge from Start Menu
2. Open Edge from Apps Menu
3. Try to Close Edge from the task bar, or the X or any other way other than Taskbar
4. Close with Task Bar and receive error but it closes

[AppGeneral.log](https://github.com/rcmaehl/MSEdgeRedirect/files/8236741/AppGeneral.log)
[AppSecurity.log](https://github.com/rcmaehl/MSEdgeRedirect/files/8236742/AppSecurity.log)
[edge.txt](https://github.com/rcmaehl/MSEdgeRedirect/files/8236743/edge.txt)
[URIFailures.log](https://github.com/rcmaehl/MSEdgeRedirect/files/8236744/URIFailures.log)

1. Leave edge open
2. Open Powershell
3. Run `gwmi Win32_Process | where { $_.name -like "msedge*.exe"} | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File $env:LOCALAPPDATA\MSEdgeRedirect\logs\edge.txt`
4. Open %localappdata%\MSEdgeRedirect\logs
6. Attach the log files

**Desktop (please complete the following information):**
 - Windows Version: [11]
 - Windows Build: [22000.556]
 - Version 21H2

**Additional context**

**Comment by rcmaehl** [comment] 2022-03-13 04:00
Please try the latest test build:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by rcmaehl** [comment] 2022-03-14 03:37
Closing per comment on #94

**Comment by shanekelly55** [comment] 2022-03-20 19:42
> Please try the latest test build:
> 
> https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

Microsoft Defenders sees this as a trojan threat.

**Comment by shanekelly55** [comment] 2022-03-28 21:53
Tried this and still doesnt work.  Facebook Messages still throw up a new tab in Chrome with the --winrt-background-task-event#.........

**Comment by rcmaehl** [comment] 2022-04-25 19:26
Please try the latest test build:

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by rcmaehl** [comment] 2022-05-08 01:08
I've been unable to reproduce on my end after d5584a6de0bd932b474c1a1a73140fc463e05303. If this is still an issue after trying the latest test build, please reopen the issue.

**Closed by rcmaehl** 2022-05-08 01:08 UTC
Labels: bug, patched?
