### ISSUE TITLE
Weather.com redirect

### ISSUE THREAD

**Issue by HamsterHam88** [rcmaehl/MSEdgeRedirect#60] opened 2022-01-14 00:33 UTC
I am getting this error when clicking the weather widget. Chrome opens but the page says this.

Access Denied
You don't have permission to access "http://www.weather.com/wx/today/?" on this server.
Reference #18.aeed655f.1642120324.241f519

**Comment by rcmaehl** [comment] 2022-01-14 17:13
Duplicate of #58 

Please use the latest test build

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by HamsterHam88** [comment] 2022-01-15 00:16
I installed the latest test build and still get this issue.

**Comment by rcmaehl** [comment] 2022-01-15 00:59
Can you provide the full URL that is giving the error?

**Comment by HamsterHam88** [comment] 2022-01-15 15:03
https://www.weather.com/wx/today/?lat=https://www.msn.com/en-gb/weather/forecast/in- ......

The rest is my location so didn't want to give the complete full URL.

**Comment by rcmaehl** [comment] 2022-01-15 19:00
Is there a ?loc=<bunch of gibberish>

![image](https://user-images.githubusercontent.com/716581/149634539-78c20d8b-19fb-46ae-a0c7-6ae341c4e369.png)

**Comment by HamsterHam88** [comment] 2022-01-15 19:23
Yes https://www.weather.com/wx/today/?lat=https://www.msn.com/en-gb/weather/forecast/in-xxxxx&lon=xxxxxxxxx?loc=eyJsIjoiQXlsZXNidXJ5IiwiciI6IkJ1Y2tpbmdoYW1zaGlyZSIsImMiOiJVbml0ZWQgS2luZ2RvbSIsImkiOiJHQiIsImciOiJlbi1nYiIsIngiOi0wLjgwMzMsInkiOjUxLjgwNTF9&weadegreetype=C&ocid=winp2octtaskbar%20&temp=C&ocid=winp2octtaskbar

**Comment by gnpaone** [comment] 2022-01-16 04:33
> Yes https://www.weather.com/wx/today/?lat=https://www.msn.com/en-gb/weather/forecast/in-xxxx&lon=xxxx?loc=eyJsIjoiQXlsZXNidXJ5IiwiciI6IkJ1Y2tpbmdoYW1zaGlyZSIsImMiOiJVbml0ZWQgS2luZ2RvbSIsImkiOiJHQiIsImciOiJlbi1nYiIsIngiOi0wLjgwMzMsInkiOjUxLjgwNTF9&weadegreetype=C&ocid=winp2octtaskbar%20&temp=C&ocid=winp2octtaskbar
> 
> I edited the link and put 'xxxx' for the parts which were location.

Hey, this is definitely patched in latest "test" build available in GitHub actions, please check it out. Update your build with that

**Comment by rcmaehl** [comment] 2022-01-16 06:37
> > Yes https://www.weather.com/wx/today/?lat=https://www.msn.com/en-gb/weather/forecast/in-xxxx&lon=xxxx?loc=eyJsIjoiQXlsZXNidXJ5IiwiciI6IkJ1Y2tpbmdoYW1zaGlyZSIsImMiOiJVbml0ZWQgS2luZ2RvbSIsImkiOiJHQiIsImciOiJlbi1nYiIsIngiOi0wLjgwMzMsInkiOjUxLjgwNTF9&weadegreetype=C&ocid=winp2octtaskbar%20&temp=C&ocid=winp2octtaskbar
> > I edited the link and put 'xxxx' for the parts which were location.
> 
> Hey, this is definitely patched in latest "test" build available in GitHub actions, please check it out. Update your build with that

Nope. They have an edge case. Working on fixing it now

**Comment by rcmaehl** [comment] 2022-01-16 07:12
Please try the latest test build now

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by HamsterHam88** [comment] 2022-01-16 19:16
Thank you, the latest test build has fixed this. Much appreciated.

**Closed** 2022-01-16 19:41 UTC
Labels: bug, patched?
