### ISSUE TITLE
0.7.4.0 causes links from outlook to open new window with home page instead of link target.

### ISSUE THREAD

**Issue by DavidPyke** [rcmaehl/MSEdgeRedirect#285] opened 2023-07-05 18:38 UTC
### Preflight Checklist

- [ ] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

Manual Update

### Install Mode

Service Mode

### Steps to reproduce

Run 0.7.4.0.  

### ✔️ Expected Behavior

Once run with Firefox as default, all links opened from Outlook open a new firefox window with the home page instead of the link in the email.  0.7.3.0 fixes the problem

### ❌ Actual Behavior

Link is opened in the existing window

### Microsoft Windows version

Windows 22H2 Build 19045.3086

### Other Software

Outlook 365
Firefox 114

**Comment by rcmaehl** [comment] 2023-07-05 20:23
Duplicate of #278. Will be looking into this this evening though!

**Closed by rcmaehl** 2023-07-05 20:23 UTC
Labels: bug, duplicate
