### ISSUE TITLE
new MS Copilot disabled?

### ISSUE THREAD

**Issue by eturk1** [rcmaehl/MSEdgeRedirect#283] opened 2023-06-30 18:09 UTC
### Preflight Checklist

- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Get Windows 11 Insider - Dev channel build 23493 to try the new Copilot
Copilot will not launch unless MSEdgeRedirect is uninstalled

### ✔️ Expected Behavior

Copilot could launch even with MSEdgeRedirect installed. 
Maybe a way to turn it off, rather than uninstall, so Copilot could be tested

### ❌ Actual Behavior

When I tap Copilot icon to launch, get and error message

### Microsoft Windows version

Build 23493 Dev Insiders

**Comment by Masamune3210** [comment] 2023-07-01 03:47
I would probably wait until the code hits release before committing to any real support. This is Microsoft, they like rewriting things at the last minute

**Comment by npfp222** [comment] 2023-07-01 17:41
I get an issue when trying to use Copilot also, I don't get any error messages, But when I click the Copilot logo in the taskbar, it just opens a blank new chrome window.

**Comment by rcmaehl** [comment] 2023-07-01 20:05
> I would probably wait until the code hits release before committing to any real support. This is Microsoft, they like rewriting things at the last minute

I'm definitely looking into it at least

**Comment by eturk1** [comment] 2023-07-02 17:53
> > I would probably wait until the code hits release before committing to any real support. This is Microsoft, they like rewriting things at the last minute
> 
> I'm definitely looking into it at least

THANKS! 
It's in Dev release so developers can have time to update code proactively.

**Comment by Suncoast-Cyclist** [comment] 2023-07-19 14:19
In a way, I look at this behavior as a feature.  I have done everything I can to eradicate all references to Cortana, bing and its ugly AI twins on my systems.  If you eventually find a way to let the new co-pilot run as Microsoft intended, it might be nice to have a checkbox in the setup process to keep the current 'blocking' behavior.

FWIW, since I have both the release version of Edge and the Dev version installed, I can get the co-pilot to work for evaluation purposes by changing the MSER settings to disable it for release version of Edge and enabling it for just the Dev Edge version.

**Comment by Nexxol** [comment] 2023-09-14 14:10
> In a way, I look at this behavior as a feature. I have done everything I can to eradicate all references to Cortana, bing and its ugly AI twins on my systems. If you eventually find a way to let the new co-pilot run as Microsoft intended, it might be nice to have a checkbox in the setup process to keep the current 'blocking' behavior.
> 
> FWIW, since I have both the release version of Edge and the Dev version installed, I can get the co-pilot to work for evaluation purposes by changing the MSER settings to disable it for release version of Edge and enabling it for just the Dev Edge version.

true but it would be nice to also disable it to use co pilot

**Comment by JoshHubi** [comment] 2023-09-23 04:49
> > I would probably wait until the code hits release before committing to any real support. This is Microsoft, they like rewriting things at the last minute
> 
> I'm definitely looking into it at least

Thank you so very much! As Copilot is releasing next week and just hit the release preview ring on my computer, I've noticed clicking on the Copilot icon in the taskbar just opens up Chrome and not the intended sidebar. MSEdgeRedirect is my everything and I'd love to use it with Copilot. ♥

**Comment by marty0678** [comment] 2023-09-26 19:07
Saw the update note, thanks for the fast response! Just updated Windows and I don't have any crashes, just opening Copilot just opens a blank Chrome tab until I uninstall MSEdgeRedirect.

**Comment by eturk1** [comment] 2023-09-26 22:45
Copilot is official. Should be no more reasons to delay a fix? 

https://www.bleepingcomputer.com/news/microsoft/windows-11-moment-4-update-released-here-are-the-many-new-features/

**Comment by rcmaehl** [comment] 2023-09-26 22:45
> Copilot is official. Should be no more reasons to delay a fix?
> 
> https://www.bleepingcomputer.com/news/microsoft/windows-11-moment-4-update-released-here-are-the-many-new-features/

Correct. I'll be releasing an update this evening

**Comment by JoshHubi** [comment] 2023-09-27 02:10
> > Copilot is official. Should be no more reasons to delay a fix?
> > https://www.bleepingcomputer.com/news/microsoft/windows-11-moment-4-update-released-here-are-the-many-new-features/
> 
> Correct. I'll be releasing an update this evening

You’re amazing! Thank you endlessly ♥

**Comment by rcmaehl** [comment] 2023-09-27 03:31
This is complete. Currently, disabling CoPilot will have the button open up Windows Settings.

If you think it should do something else (or nothing at all), that feedback is appreciated.

**Comment by marty0678** [comment] 2023-09-27 04:01
Thanks for the fast response time! Copilot launches now, however, all links it generates take you to an about:blank page. Not sure if that's something easily fixable or not / if I should open a new ticket.

**Comment by rcmaehl** [comment] 2023-09-27 04:06
> Thanks for the fast response time! Copilot launches now, however, all links it generates take you to an about:blank page. Not sure if that's something easily fixable or not / if I should open a new ticket.

FFFFFFFFFFFFFFFFFFFFFFFFFFFFantastic

Unfortunately, I'll take a look at this tomorrow as it works fine in my HyperV environment

**Comment by marty0678** [comment] 2023-09-27 04:13
Update: Testing different options and Service Mode seems fine, just Active Mode results in the about:blank pages.

**Comment by JoshHubi** [comment] 2023-09-27 05:35
> Thanks for the fast response time! Copilot launches now, however, all links it generates take you to an about:blank page. Not sure if that's something easily fixable or not / if I should open a new ticket.

Stange! Copilot is working for me but it's opening all the links in Edge instead. 

https://github.com/rcmaehl/MSEdgeRedirect/assets/931716/91b9174e-88a0-4382-b394-e4ec702ee517

**Comment by rcmaehl** [comment] 2023-09-27 10:46
> > Thanks for the fast response time! Copilot launches now, however, all links it generates take you to an about:blank page. Not sure if that's something easily fixable or not / if I should open a new ticket.
> 
> Stange! Copilot is working for me but it's opening all the links in Edge instead.
> 
>  Recording.2023-09-27.013508.mp4

Yes, this is intended behavior and what I'm getting on my machine. Since CoPilot is Edge, I am not currently able to redirect links from there as it's the same as if you're just clicking a link in the Edge Browser.

I'm looking into ways around this (read: Browser Extensions) but I'm not a webdev nor do I know if the extension stores would even allow the functionality I'm considering (Links -> URI -> MSEdgeRedirect -> Preferred Browser)

**Comment by JoshHubi** [comment] 2023-09-27 11:09
> > > Thanks for the fast response time! Copilot launches now, however, all links it generates take you to an about:blank page. Not sure if that's something easily fixable or not / if I should open a new ticket.
> > 
> > 
> > Stange! Copilot is working for me but it's opening all the links in Edge instead.
> > Recording.2023-09-27.013508.mp4
> 
> Yes, this is intended behavior and what I'm getting on my machine. Since CoPilot is Edge, I am not currently able to redirect links from there as it's the same as if you're just clicking a link in the Edge Browser.
> 
> I'm looking into ways around this (read: Browser Extensions) but I'm not a webdev nor do I know if the extension stores would even allow the functionality I'm considering (Links -> URI -> MSEdgeRedirect -> Preferred Browser)

Wonderful! Thank you for clarifying. The browser extension idea is a great one. On free time I’d love to prototype an extension that can potentially do exactly what you are proposing. MSEdgeRedirect could be a default app for a new link type (ex: MSEdgeRedirect://) and the extension could bind to an OnClicked event, sniff the URL that was clicked, prevent the default function of opening in a new tab/window, and open it as this new link type with the URL to redirect formatted into it. 

Inspired!

**Comment by rcmaehl** [comment] 2023-09-27 12:01
> Wonderful! Thank you for clarifying. The browser extension idea is a great one. On free time I’d love to prototype an extension that can potentially do exactly what you are proposing. MSEdgeRedirect could be a default app for a new link type (ex: MSEdgeRedirect://) and the extension could bind to an OnClicked event, sniff the URL that was clicked, prevent the default function of opening in a new tab/window, and open it as this new link type with the URL to redirect formatted into it.

Correct! Feel free to design a prototype if you'd like. I probably won't use `MSEdgeRedirect` for the URI name as interoperability / sharing is common in the F!@K MSEdge GitHub Group (Chrometana Pro works with MSER which works with AveYo's Edge Removal, et al).

Heck, reusing `Microsoft-Edge://` would probably work as well. If MSER/Wedge/et al isn't installed, it would just open things up as normal in Edge and never be "broken".

**Comment by marty0678** [comment] 2023-09-27 18:11
https://github.com/rcmaehl/MSEdgeRedirect/assets/49799843/4054cc5d-b801-4958-8c6b-b04d6b94b8fb

I tried re-installing again today to play more around with it, and I'm still getting the about:blank pages on some links, but on others (as shown in this video) just blocks out the whole webview. 

Happy to help test/reproduce things if it's helpful.

**Comment by rcmaehl** [comment] 2023-09-27 19:27
I get off work from my main job here in about 2 hours and will create a test build here in 3ish

**Comment by marty0678** [comment] 2023-09-27 19:36
I've noticed the links that get blocked like this all work when I middle mouse click the links, they open in a new Edge tab as expected. Also if you don't click the links inline, and click them in the source section they are also fine. I haven't seen the about:blank thing since the few reboots/re-installs, but I have seen reports of this error message just appearing in Edge in general.

Actually, I don't think this is an issue with MSRedirect the more I play with it. I just uninstalled it, and I'm getting the same issue. So this might just be a broken Copilot thing.

**Comment by rcmaehl** [comment] 2023-09-28 17:10
> Actually, I don't think this is an issue with MSRedirect the more I play with it. I just uninstalled it, and I'm getting the same issue. So this might just be a broken Copilot thing.

I'm going to close this for now. If I get additional reports that show MSER is somehow breaking it I'll create a new ticket and get it patched.

**Closed by rcmaehl** 2023-09-28 17:10 UTC
Labels: bug
