### ISSUE TITLE
Still sends the search queries to bing

### ISSUE THREAD

**Issue by aiquiral** [rcmaehl/MSEdgeRedirect#47] opened 2021-12-26 11:07 UTC
It does open the preferred browser with the search result in the preferred search engine when 'enter' key is pressed, but the query goes to Bing upon typing the query in the Windows search.

Look at the screenshots and you will understand the issue.

Librewolf (JS is on)- https://imgur.com/a/undZl1y
Ungoogled Chromium (my default browser) (No JS) - https://imgur.com/a/cg227lD

 - OS: Windows 11 Home Single Language
 - Build: 21H2

The search results displayed in Windows search are from Bing not from the search engine I chose during the installation.

**Comment by rcmaehl** [comment] 2021-12-26 22:13
> Librewolf (JS is on)- https://imgur.com/a/undZl1y

This one is likely due to Service Mode performance issues. These are heavily improved in 0.6.0.0 which should be released by end of month. For now, I'd recommend uninstalling and reinstalling in active mode.

>Ungoogled Chromium (my default browser) (No JS) - https://imgur.com/a/cg227lD

This one I can't fix without replacing Windows System Files.

**Comment by rcmaehl** [comment] 2021-12-26 22:13
Closing as duplicate of #45

**Closed by rcmaehl** 2021-12-26 22:13 UTC
Labels: enhancement, in-progress
