### ISSUE TITLE
Flags as malware when downloading

### ISSUE THREAD

**Issue by jayc331** [rcmaehl/MSEdgeRedirect#212] opened 2022-10-22 16:25 UTC
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Unsure

### Steps to reproduce

Downloading from Github website on Firefox flags as malware.

![image](https://user-images.githubusercontent.com/105918957/197350384-ad0ec5fe-fa4b-4930-b3c7-66cb77e983d4.png)

### ✔️ Expected Behavior

Downloads

### ❌ Actual Behavior

Flags as virus :wtf:

### Microsoft Windows version

Windows 11 Pro - 21H2 (22000.1098)

### Other Software

Firefox 106.0.1 (64-bit)

**Comment by Masamune3210** [comment] 2022-10-23 03:45
Unfortunately nothing the project or any of us can do anything about other than reporting it as a false positive and waiting for Google to decide that its in fact a false positive and remove the flag. The project contains no malware, but unfortunately, open source projects tend to get flagged like this for numerous reasons. You see it all over different projects on GitHub and other sites like it

**Comment by Volt-Ampere** [comment] 2022-10-23 16:40
a bit of a long-winded approach but i got it to work. I have google drive desktop synced on my computer, I download the .EXE on my phone, upload it on drive, then i run the exe from the google drive folder on my computer.

**Comment by Masamune3210** [comment] 2022-10-23 17:23
For future reference, you can also just go to the Downloads page in Chrome iirc and tell it that yes you are sure download the file

**Comment by jayc331** [comment] 2022-10-23 17:43
My concern was the fact that it's being flagged as malware rather than asking for a way to ignore the warnings.

**Comment by Masamune3210** [comment] 2022-10-23 17:47
I know, was talking to the other person. It's flagged incorrectly, not much we can do about it

**Comment by Volt-Ampere** [comment] 2022-10-24 01:40
> For future reference, you can also just go to the Downloads page in Chrome iirc and tell it that yes you are sure download the file

lol thanks for the tip, that was so much simpler. I rarely open the downloads page I didn't know it was possible to tell the browser to keep the file from that page.

**Comment by jayc331** [comment] 2022-10-24 11:55
Unresolved

**Comment by Masamune3210** [comment] 2022-10-25 10:56
You are reading too much into this, it happens all the time with things completely unrelated to anything Microsoft is involved with. It has to do with how heuristic detection engines work, if the network hasn't seen a particular file a lot, and I mean on a LOT of computers, its more likely to immediately assume its malicious and try to quarantine or refuse its download until it is manually reviewed. Doubly so if not triply if the file in question doesn't adhere to "normal" practices or have a code signature

**Comment by gluons** [comment] 2022-10-25 14:22
**VirusTotal result:**

[![ภาพ](https://user-images.githubusercontent.com/4688092/197799426-37f03d40-95ac-47b6-835f-4d24485d81a9.png)](https://www.virustotal.com/gui/file/745b492789c8905457d43cce7761de0510f69c70e1a8b316d680fede45ecff61/detection)

**Comment by Masamune3210** [comment] 2022-10-25 23:08
5 out of a gigantic list of venders only furthers proof its a false positive. Especially since half of them I've never even heard of and the one I have is known for constantly having false positives

**Comment by rcmaehl** [comment] 2022-10-26 23:12
Duplicate of #37

Click "View All Downloads" to keep the file

![image](https://user-images.githubusercontent.com/716581/198155835-4cea1901-5414-4550-b7cd-202e5b6489f2.png)

**Closed by rcmaehl** 2022-10-26 23:12 UTC
Labels: bug
