### ISSUE TITLE
MS Edge cannot update after installing 0.7.3

### ISSUE THREAD

**Issue by dinamites** [rcmaehl/MSEdgeRedirect#241] opened 2023-01-20 12:54 UTC
Hello.
I am a user of your exzcellent software. After updating to 0.7.3, I noticed MS EDGE cannot update itself anymore with an error 
![edge error](https://user-images.githubusercontent.com/27813039/213699436-9ae5892d-8d55-4d5d-92a1-ab5694479e3f.jpg)

No issues with previous version. The error disappears if I uninstall MSedgeredirect.

Thanks and keep up the good job.

**Comment by rcmaehl** [comment] 2023-01-20 14:08
> Sorry, I am new to GitHub and I am not a developer. I just noticed that other people already flagged the bug. Please disregard my entry.

Yep. Duplicate of #239. Closing.

**Closed by rcmaehl** 2023-01-20 14:08 UTC
