### ISSUE TITLE
Breaking

### ISSUE THREAD

**Issue by kieranhawk** [rcmaehl/MSEdgeRedirect#369] opened 2023-12-28 11:52 UTC
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Just installed, did everything the instructions say, it started to act like the video, reloaded several times, but still

### ✔️ Expected Behavior

To work

### ❌ Actual Behavior

https://github.com/rcmaehl/MSEdgeRedirect/assets/148392478/b9e726a3-a586-43d0-85b4-19325a30b9f0

### Microsoft Windows version

Sorry, can’t check due to not working

**Comment by rcmaehl** [comment] 2023-12-28 14:29
Duplicate of #367

**Closed by rcmaehl** 2023-12-28 14:29 UTC
Labels: bug
