### ISSUE TITLE
win search invokes the edge browser and searches with Google instead of bing

### ISSUE THREAD

**Issue by thomasTAT** [rcmaehl/MSEdgeRedirect#298] opened 2023-08-06 10:23 UTC
### Description of the new feature / enhancement

win search invokes the edge browser and searches with Google instead of bing.

### Scenario when this would be used?

I want to keep using edge but not bing.

**Comment by rcmaehl** [comment] 2023-08-06 16:03
Duplicate of #242

Not currently able to be implemented but it's planned. 

Currently, I'd recommend Chrometana Pro. Use the following options in Edge's Extension Page:

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/716581/72cc7850-92d1-44e3-bc8c-a4e9d5cb4bec)

**Closed by rcmaehl** 2023-08-06 16:03 UTC
Labels: enhancement
