### ISSUE TITLE
Clicking on information card in taskbar feed produces AutoItError

### ISSUE THREAD

**Issue by mariellep** [rcmaehl/MSEdgeRedirect#198] opened 2022-10-02 18:56 UTC
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

I updated to the latest stable version (V0.7.1.0). 

Clicking on any web link in the start menu is working just fine, but the feed links aren't opening at all now. Example:

![image](https://user-images.githubusercontent.com/3780369/193470788-e3e8ed41-7e37-4290-9071-213bd54cc116.png)

Clicking on any of the links will cause this window to pop up:
![image](https://user-images.githubusercontent.com/3780369/193470851-714cf6db-f66a-463b-ae54-d2c7ad990598.png)

Please note that AppFailures, AppSecurity, and PEBIAT files in the logs folder are blank. URIFailures and AppGeneral aren't blank but the timestamps don't correspond to the failure. 

### Microsoft Windows version

21H1 Build 19043.2006

**Comment by rcmaehl** [comment] 2022-10-02 19:26
Duplicate of #195

Please try the latest test build and comment via the link to #195 if it's still broken

**Closed by rcmaehl** 2022-10-02 19:26 UTC
Labels: bug
