### ISSUE TITLE
too many tabs

### ISSUE THREAD

**Issue by 14paavang** [rcmaehl/MSEdgeRedirect#66] opened 2022-01-25 04:09 UTC
when i use windows search and then it tries to open edge, it opens 100 tabs instead of 1
<img width="960" alt="image" src="https://user-images.githubusercontent.com/81815334/150909298-0cd930af-f52a-4ccd-91ed-6ac3cb7f447f.png">

**Comment by rcmaehl** [comment] 2022-01-25 13:10
Duplicate of #45. I would recommend uninstalling and selecting 'Active Mode' during reinstall if you're encountering this issue. It should be resolved by #36 later this month.

**Closed** 2022-01-25 23:24 UTC
Labels: bug, duplicate

**Comment by 14paavang** [comment] 2022-01-26 07:26
How do i uninstall? the program is not showing up in windows

**Comment by rcmaehl** [comment] 2022-01-26 13:17
It can be uninstalled using the following steps:

![image](https://user-images.githubusercontent.com/716581/151169089-3f356701-e933-4b42-beb2-297125f696e2.png)

![image](https://user-images.githubusercontent.com/716581/151169366-93fea4b6-d3d2-440c-974a-0f670f3b488d.png)

Alternatively, navigate to where you downloaded the file and run:

![image](https://user-images.githubusercontent.com/716581/151169672-0b835015-aa56-44a7-9b9e-fea3ad917496.png)

**Comment by 14paavang** [comment] 2022-01-27 02:30
i'm afraid i am using windows 11 and it is not showing up in add or remove programs, and I am not able to figure out where it is on my computer

**Comment by rcmaehl** [comment] 2022-01-27 02:31
It is either in `C:\Program Files` or `%localappdata%`

**Comment by 14paavang** [comment] 2022-01-27 02:32
what is the place where it installs itself by default?

**Comment by rcmaehl** [comment] 2022-01-27 02:43
`%localappdata%`

**Comment by 14paavang** [comment] 2022-01-27 02:43
ok, found it thanks
