### ISSUE TITLE
Allow users to opt out of being prompted to update the IFEO exclusion file

### ISSUE THREAD

**Issue by abhitrueprogrammer** [rcmaehl/MSEdgeRedirect#196] opened 2022-10-02 09:17 UTC
### Description of the new feature / enhancement

This is close to a bug report as a feature request. The dialog to update the IFEO exclusion file is persistently shown to the user at random intervals, with no option to opt out of being shown the dialog. It is even showed to the user when they have uninstalled this programme[at least if you install it using the binary].

### Scenario when this would be used?

Whenever a user wants edge deflector to get out of the way. 

### Supporting information

![image](https://user-images.githubusercontent.com/67090539/193446851-062d44e8-8fa6-45de-b929-370b65b4ef2c.png)

**Comment by rcmaehl** [comment] 2022-10-02 19:24
Duplicate of #146. Currently working on tho!

**Closed by rcmaehl** 2022-10-02 19:24 UTC
Labels: enhancement
