### ISSUE TITLE
Need to still use edge

### ISSUE THREAD

**Issue by gameking1990** [rcmaehl/MSEdgeRedirect#144] opened 2022-06-09 03:50 UTC
### Description of the new feature / enhancement

Ability to still use Edge

### Scenario when this would be used?

I used to use edge deflector just so my browser's search engine is used if I do a web search from the start menu. Was gonna try this out but, Edge is not usable, I hate Bing but still use Edge. Can this be resolved?

**Comment by rcmaehl** [comment] 2022-06-09 14:18
Edge should still work. Which mode did you install MSER in and where you getting a specific error?

**Comment by gameking1990** [comment] 2022-06-11 21:59
![image](https://user-images.githubusercontent.com/107165331/173206273-e143efaf-ffa1-43ef-b77f-b41135418864.png)

**Comment by gameking1990** [comment] 2022-06-11 22:00
I get this when trying to install

**Comment by gameking1990** [comment] 2022-06-11 22:00
Downloaded the latest stable release from GitHub

**Comment by gameking1990** [comment] 2022-06-11 22:08
I seem to have had a successful install now using Chocolatey. However, when I try to do a web search in the start menu. I get the above message. Previously I was downloading the "latest stable release" from GitHub and when double clicking on that, I would get the same above message.

**Comment by gameking1990** [comment] 2022-06-11 22:10
I should add it does not even allow me to launch Edge

**Comment by rcmaehl** [comment] 2022-06-12 17:28
> ![image](https://user-images.githubusercontent.com/107165331/173206273-e143efaf-ffa1-43ef-b77f-b41135418864.png)

Open 
![image](https://user-images.githubusercontent.com/716581/173245466-6be3c588-e599-42dc-ae56-7dfc7efc7281.png)

Set something other than Edge as Web Browser

![image](https://user-images.githubusercontent.com/716581/173245487-000da639-c615-45ad-9dce-f4f78e136d08.png)

You can still use Edge afterwards, just not as the default browser. This will change in a future release.

**Comment by rcmaehl** [comment] 2022-06-12 17:29
Closing as duplicate of #124

**Closed by rcmaehl** 2022-06-12 17:29 UTC
Labels: enhancement, need info
