### ISSUE TITLE
Europe Mode Machine Region not applying

### ISSUE THREAD

**Issue by eiqnepm** [rcmaehl/MSEdgeRedirect#461] opened 2024-09-17 21:05 UTC
### Preflight Checklist

- [ ] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Europe Mode

### Steps to reproduce

Install using Europe Mode leaving everything as default

### ✔️ Expected Behavior

All the current are replaced by new values

### ❌ Actual Behavior

App displays that the current values are changed to the new values, but restarting the app still displays the old machine region, rebooting is the same.

### Microsoft Windows version

22631.4169

**Comment by eiqnepm** [comment] 2024-09-17 22:49
I was able to change the registry key responsible for the machine region value using `chntpw` on a bootable Linux USB, it is not persistent, but I am still unable to uninstall Edge

**Comment by micwoj92** [comment] 2024-09-17 23:32
Hi, is this not duplicate of https://github.com/rcmaehl/MSEdgeRedirect/issues/404?

**Comment by eiqnepm** [comment] 2024-09-18 00:23
> Hi, is this not duplicate of https://github.com/rcmaehl/MSEdgeRedirect/issues/404?

Thanks! After editing the machine region registry using Linux, and then repairing Edge, the uninstall option appeared.

**Comment by micwoj92** [comment] 2024-09-18 06:04
Closing as duplicate then

**Closed by micwoj92** 2024-09-18 06:04 UTC
Labels: bug, duplicate
