### ISSUE TITLE
Outlinks in some apps open in Edge anyway on Windows 11 build 22621.1702

### ISSUE THREAD

**Issue by JosephM101** [rcmaehl/MSEdgeRedirect#268] opened 2023-05-26 12:13 UTC
I'm running Windows 11 build 22621.1702 in a VM. I tried the `microsoft-edge:https://google.com` troubleshooting method, which works just fine. But if I try to open a link, say, from the Settings app _(ex. System -> Storage -> Help with Storage ->Using disk cleanup)_, it opens in Edge (and for some reason crashes immediately, but I'm not sure if that's related).
 
What's even more weird is that a couple of the links in the Settings app _did_ open in Firefox. For example, in the Windows Update section:
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/28277730/61a2c5cf-5d0a-4e2e-b4b4-5fb922f2a6db)
The rest tried to open in Edge.

I'm running MSEdgeRedirect, version 0.7.3.0 in Active mode, as was recommended.

**Comment by rcmaehl** [comment] 2023-05-26 12:14
That's... something

**Comment by HarshalKudale** [comment] 2023-05-26 18:19
I also encountered this issue. Mostly I have found out that first link opens in default browser and then it starts going to edge and crashes. Also if edge is already open then it opens in edge without crash.

**Comment by rcmaehl** [comment] 2023-05-28 04:21
> I'm running Windows 11 build 22621.1702 in a VM. I tried the `microsoft-edge:https://google.com` troubleshooting method, which works just fine. But if I try to open a link, say, from the Settings app _(ex. System -> Storage -> Help with Storage ->Using disk cleanup)_, it opens in Edge (and for some reason crashes immediately, but I'm not sure if that's related).
> 
> What's even more weird is that a couple of the links in the Settings app _did_ open in Firefox. For example, in the Windows Update section: ![image](https://user-images.githubusercontent.com/28277730/241216063-61a2c5cf-5d0a-4e2e-b4b4-5fb922f2a6db.png) The rest tried to open in Edge.
> 
> I'm running MSEdgeRedirect, version 0.7.3.0 in Active mode, as was recommended.

Was a duplicate of #143. will be fixed in 0.8.0.0. Just ironing out some bugs.

**Closed by rcmaehl** 2023-05-28 04:21 UTC
