### ISSUE TITLE
Cannot open Display adapter properties window or color management app when MSEdgeRedirect is running.

### ISSUE THREAD

**Issue by Secre-C** [rcmaehl/MSEdgeRedirect#415] opened 2024-04-21 02:17 UTC
### Preflight Checklist

- [ ] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Deployment (Chocolatey, Winget, Etc)

### Install Mode

N/A or Unsure

### Steps to reproduce

install msEdgeRedirect and make sure it's running.
open the start menu, search for color management, and hit enter.

alternatively:
open display settings -> advanced display -> Display Adapter properties for display

### ✔️ Expected Behavior

the color management window/display adapter properties to open

### ❌ Actual Behavior

Nothing happens. the window does not open.

### Microsoft Windows version

23H2 Build 22635.3495

**Comment by rcmaehl** [comment] 2024-04-21 02:23
If you installed via Chocolatey, you may be a couple versions behind. Our automatic deployment for new versions to their site has screwed up and I'm still working on fixing it. Can you verify if you're running 0.7.5.3?

**Comment by Secre-C** [comment] 2024-04-21 02:57
I installed via Winget, and I can confirm that I'm on 0.7.5.3

**Comment by rcmaehl** [comment] 2024-04-21 03:14
I was able to reproduce on Win11 23H2 Build 22631.3447.

Oddly enough, can't reproduce the issue on Windows 10. I'll try to get Windows 11 on parity,

**Comment by rcmaehl** [comment] 2024-04-21 03:26
Ah. That's why. I haven't released the version with the fix yet. My Win10 device is just running the CI build. Duplicate of #395 and will be fixed next release!

**Closed by rcmaehl** 2024-04-21 03:26 UTC
Labels: bug
