### ISSUE TITLE
Asus Rog causing "Invalid Parameter"

### ISSUE THREAD

**Issue by TheRiftreaper** [rcmaehl/MSEdgeRedirect#162] opened 2022-08-08 22:07 UTC
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

I get a frequent popup on my screen from the redirect app.  I attached a screen shot and a zip file with the logs. Please help me fix the issue.

### ✔️ Expected Behavior

redirect works

### ❌ Actual Behavior

Error popup message

### Microsoft Windows version

21H2 Build 19044.1865

### Other Software

[Logs.zip](https://github.com/rcmaehl/MSEdgeRedirect/files/9285276/Logs.zip)
![error](https://user-images.githubusercontent.com/110703282/183522721-e5e905e2-9009-44c9-87a5-df7969cef3d0.jpg)

**Comment by rcmaehl** [comment] 2022-08-08 22:53
Odd.

Are you potentially running an Asus machine or ROG software?

**Comment by TheRiftreaper** [comment] 2022-08-09 11:56
> Odd.
> 
> Are you potentially running an Asus machine or ROG software?

Yes, the Asus Armory software. Looks like it was interacting with the MSEdgeRedirect app. Now i just need to figure out why  the ASUS app keeps opening a URL.

Thank you for your help.

**Comment by rcmaehl** [comment] 2022-08-09 14:23
> Yes, the Asus Armory software. Looks like it was interacting with the MSEdgeRedirect app. Now i just need to figure out why the ASUS app keeps opening a URL.

Based on the logs provided. It's opening 127.0.0.1:1042. It looks like it might be for communicating with the "ASUS Framework Service" based on initial searches, but I'm asking around to be sure.

I've added a potential fix in debdf0b68bcc3f7223a8e9ee21775041ca2e36bc which will be in 0.7.1.0 released at the end of the week.

**Comment by rcmaehl** [comment] 2022-08-09 16:25
> Yes, the Asus Armory software. Looks like it was interacting with the MSEdgeRedirect app. Now i just need to figure out why the ASUS app keeps opening a URL.
> 
> Thank you for your help.

Per the Official Asus ROG discord, Armory is "build on HTML", which I'm assuming means that it's basically a msedgewebview applet / a webpage within an app.

Please try the latest test build and let me know if Armory still works. If not, I'll add in an exception to fix it.

**Comment by TheRiftreaper** [comment] 2022-08-10 00:39
Everything is working correctly now with the latest test build.

**Comment by niZyalB** [comment] 2022-08-10 00:47
I also have an ASUS machine and everytime I open Armoury Crate now (also on boot), it opens the 127.0.0.1:1042 in my browser.

**Comment by TheRiftreaper** [comment] 2022-08-10 01:01
> I also have an ASUS machine and everytime I open Armoury Crate now (also on boot), it opens the 127.0.0.1:1042 link in my browser.

I had ths too. After I installed the test build of MSEdgeRedirect, I had to uninstall and reinstall the entire ASUS Armory package to get the url to stop opening.

**Comment by rcmaehl** [comment] 2022-08-10 02:43
> I also have an ASUS machine and everytime I open Armoury Crate now (also on boot), it opens the 127.0.0.1:1042 link in my browser.

> I had ths too. After I installed the test build of MSEdgeRedirect, I had to uninstall and reinstall the entire ASUS Armory package to get the url to stop opening.

Welp. That's not what should be happening. Added a full on exception for this to stop occurring in the [latest test build](https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip).

**Comment by TheRiftreaper** [comment] 2022-08-11 00:51
Thank you

**Comment by t0rzz** [comment] 2022-08-11 00:51
> > I also have an ASUS machine and everytime I open Armoury Crate now (also on boot), it opens the 127.0.0.1:1042 link in my browser.
> 
> > I had ths too. After I installed the test build of MSEdgeRedirect, I had to uninstall and reinstall the entire ASUS Armory package to get the url to stop opening.
> 
> Welp. That's not what should be happening. Added a full on exception for this to stop occurring in the [latest test build](https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip).

Tested, restarted, no more errors popping up on logging in. Good job. (yes, I have Armoury Crate installed and running ROG software on an ASUS motherboard)

**Closed** 2022-08-16 17:40 UTC
Labels: bug, patched?

**Comment by TheRealDjElite** [comment] 2022-08-18 22:46
The TEST build fixed the same issue I was having caused by ASUS Armoury Crate. Thank you. 🤙🏽
