### ISSUE TITLE
Breaks Copilot on 22H2

### ISSUE THREAD

**Issue by LoosGuccreen** [rcmaehl/MSEdgeRedirect#313] opened 2023-09-26 17:36 UTC
### Preflight Checklist

- [X] Running `microsoft-edge:https://google.com` redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Install MSEdgeRedirect then try to open Copilot on a 22H2 Windows 11.

### ✔️ Expected Behavior

Copilot (the IA thing from Microsoft) should open in a side view on the right of the screen (likely using Edge).

### ❌ Actual Behavior

A blank window of my default browser (Firefox here) opens.

### Microsoft Windows version

22H2

**Comment by rcmaehl** [comment] 2023-09-26 18:54
Duplicate of #283. Will have an update for this at the end of the day.

**Closed by rcmaehl** 2023-09-26 18:54 UTC
Labels: bug
