### ISSUE TITLE
Hey, i fresh installed the EXE problem with the widgets.

### ISSUE THREAD

**Issue by alonwillmakeit** [rcmaehl/MSEdgeRedirect#206] opened 2022-10-08 00:58 UTC
So i installed the exe and it works perfectly for redirects from the search for the web from the search bar.
but as for the widgets i get an error
![image](https://user-images.githubusercontent.com/45737690/194679651-8080aad4-05ff-4fc3-8f66-1555dd109778.png)

Anyone encountered?

**Comment by ElitePheonix2009** [comment] 2022-10-08 02:25
Latest builds have addressed these issues, rcmaehl linked this build in #197:
https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/0.8.0.0-dev/mser.zip

**Comment by rcmaehl** [comment] 2022-10-08 20:11
Yep, Duplicate of #197

**Closed by rcmaehl** 2022-10-08 20:11 UTC
