### ISSUE TITLE
opens two windows and hundreds of tabs

### ISSUE THREAD

**Issue by eturk1** [rcmaehl/MSEdgeRedirect#44] opened 2021-12-21 23:31 UTC
Just installed to try. Really scary that it opens one Chrome window with the search terms in Bing (though set for Google during install AND opens a second window with hundreds of tabs. Killing Chrome won't stop it easily.

Behaving like malware but bitdefender isn't warning about file.

Video of problem:
https://user-images.githubusercontent.com/525280/147010766-549c2d27-8c6a-4f5c-93f1-df36998e408e.mp4

**Comment by rcmaehl** [comment] 2021-12-22 00:41
Duplicate of #45

**Closed by rcmaehl** 2021-12-22 00:41 UTC
