### ISSUE TITLE
Functionality does not work (Edge manually uninstalled)

### ISSUE THREAD

**Issue by Janmm14** [rcmaehl/MSEdgeRedirect#59] opened 2022-01-12 17:43 UTC
**Check List**
- [x] The App appears in the system tray
- [ ] Running `microsoft-edge:https://google.com` redirects successfully

**Describe the bug**\
I have edge deinstalled from my system using the command prompt solution described here: https://www.tomsguide.com/how-to/how-to-uninstall-microsoft-edge

Running `microsoft-edge:https://google.com` in Windows+R causes an errors to appear.

Is there a way to get this working without edge being properly installed?

![](https://user-images.githubusercontent.com/3533175/149193138-f20e3386-a671-4983-9564-e571b497aefd.png)
![](https://user-images.githubusercontent.com/3533175/149193459-d5143181-38dc-4c81-9f4e-1c846dd63971.png)
![](https://user-images.githubusercontent.com/3533175/149193393-61abf767-e0dc-4b0d-ba51-e83eaba09551.png)

**Comment by rcmaehl** [comment] 2022-01-12 17:56
Duplicate of #26.

I would recommend installing at least [Edge Canary](https://www.microsoftedgeinsider.com/en-us/download/canary) which installs to Appdata until I figure out a solution to this.

**Closed** 2022-01-12 20:20 UTC
Labels: bug
