### ISSUE TITLE
Redirect non-Edge Bing to preferred search engine

### ISSUE THREAD

**Issue by ArcaEge** [rcmaehl/MSEdgeRedirect#290] opened 2023-07-27 10:53 UTC
### Description of the new feature / enhancement

Some Microsoft programs don't use the `microsoft-edge:` handler but use `https://www.bing.com/...`, therefore redirecting to Bing. Allow redirection of those links to the preferred search engine.

### Scenario when this would be used?

Visual Studio uses `https:` but also redirects to Bing:

https://github.com/rcmaehl/MSEdgeRedirect/assets/40526225/e41850ab-e40e-49c7-a500-658bc08ab4d5

### Supporting information

I am aware that Chrometana exists, however it would be useful to have this functionality built into the app

**Comment by rcmaehl** [comment] 2023-07-27 14:11
Due to how MSEdgeRedirect is currently setup, this isn't able to be implemented. However, it will be an available feature once I allow MSEdgeRedirect to Redirect URLs to a Browser other than the default one.

**Comment by rcmaehl** [comment] 2023-07-31 17:43
Closing as duplicate of #242

**Closed by rcmaehl** 2023-07-31 17:43 UTC
Labels: enhancement
